vh_ClusterData.php
vh_abortTask.php
vh_addClusterSlot.php
vh_addNotepadIP.php
vh_addUpdate.php
vh_addshit.php
vh_attackCenterInfo.php
vh_attackCompany.php
vh_attackCompany2.php
vh_attackCompany3.php
vh_botnetInfo.php
vh_buyBonusBox.php
vh_clusterAdd.php
vh_clusterDecision.php
vh_clusterJoin.php
vh_clusterKick.php
vh_clusterLeave.php
vh_clusterMessage.php
vh_clusterPromote.php
vh_clusterSystem.php
vh_createMission.php
vh_finishAll.php
vh_finishTask.php
vh_getClusterMember.php
vh_getClusterRequests.php
vh_getDaily.php
vh_getDailyData.php
vh_getEvents.php
vh_getImg.php
vh_getNotepadData.php
vh_getProfileInfo.php
vh_getSysLog.php
vh_loadRemoteData.php
vh_mails.php
vh_openAllBonus.php
vh_openFreeBonus.php
vh_ranking.php
vh_rankingCluster.php
vh_register.php
vh_removeNotepadIP.php
vh_removeSpyware.php
vh_removeSpywareRemote.php
vh_requestPass.php
vh_scan.php
vh_scanHost.php
vh_scanIP.php
vh_scanTag.php
vh_spywareInfo.php
vh_spywareUpload.php
vh_startDDoS.php
vh_tasks.php
vh_tournamentData.php
vh_trTransfer.php
vh_update.php
vh_updateInfo.php
vh_updateNotepadContent.php
vh_upgradeBotnet.php
vh_upgradeClusterSoftware.php